### ISSUE TITLE
Copy into clipboard not working

### ISSUE THREAD

**Issue by manfredmjka** [muennich/urxvt-perls#94] opened 2019-11-13 08:48 UTC
Hey! 

I'm having an issue with the `keyboard-select-clipboard` feature: 
I set the following inside my `.Xresources`: 

```
#include "/home/xxx/.vim/plugged/edge/xresources/edge-dark.Xresources"

*background: [80]black

URxvt.perl-lib: /usr/lib/urxvt/perl

URxvt*highlightColor:     white
URxvt*highlightTextColor: black
URxvt*cursorColor:        white
URxvt*cursorColor2:       black
URxvt*pointerColor:       white
URxvt*pointerColor2:      black

URxvt*font:           xft:DejaVu Sans Mono:pixelsize=12
URxvt*scrollBar:      false
URxvt*internalBorder: 32
URxvt*depth:          32
URxvt*saveLines:      4000
URxvt*cursorBlink:    true

URxvt*perl-ext-common: default,matcher,keyboard-select,font-size
URxvt*url-launcher:    xdg-open
URxvt*matcher.button:  1
URxvt*matcher.rend.0:  Uline Bold fg5
URxvt*fading:          false

Xcursor.size:          16

URxvt.keysym.Shift-Up: command:\033]720;1\007
URxvt.keysym.Shift-Down: command:\033]721;1\007

URxvt.keysym.M-Escape: perl:keyboard-select:activate
URxvt.keysym.M-Plus:   font-size:increase
URxvt.keysym.M-Minus:  font-size:decrease
URxvt.keysym.M-0:      font-size:reset

URxvt.keyboard-select.clipboard: true

```

Copying something with `y` copies just to the `primary`. I checked this with 

```sh 
xclip -o -selection clipboard # returns nothing 
xclip -o -selection primary # returns the copied string
``` 

My system: 
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
urxvt-perls 2.2-2
```

Is there any misconfiguration in my settings? Any help would by really appreciated, i like this tool a lot! 
Thanks in advice

**Comment by muennich** [comment] 2019-11-13 10:59
This is a duplicate of #89. I will release a new version right now.

**Closed by muennich** 2019-11-13 10:59 UTC

**Comment by manfredmjka** [comment] 2019-11-13 11:02
Thanks!
