### ISSUE TITLE
url-select: selection of long urls

### ISSUE THREAD

**Issue by manolomartinez** [muennich/urxvt-perls#61] opened 2015-06-18 08:16 UTC
When urxvt wraps a line containing an url, url-select only catches the first line.

That is, for example, if the window is wide enough for the url to be displayed in one physical line, url-select will underline the whole url. If the url needs to be wrapped, only the first line will be underlined. This seems to happen only in terminal applications, although apparently not when working on the shell proper.

The attached images (displaying a long url in vim in a wide window and a not so wide one) show what I mean.

Thanks!

![screenshot](https://cloud.githubusercontent.com/assets/2140956/8226889/e59ed250-15a2-11e5-83ce-e4cfbdbfffa5.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/2140956/8226895/f0fdba44-15a2-11e5-9624-4b947db0ac5e.jpg)

**Comment by muennich** [comment] 2015-06-18 18:14
Duplicate of issue #6.

**Closed by muennich** 2015-06-18 18:14 UTC
