### ISSUE TITLE
terminal width being too narrow makes links unyankable

### ISSUE THREAD

**Issue by sorezzz** [muennich/urxvt-perls#85] opened 2017-11-13 18:23 UTC
https://i.imgur.com/DmQwRIG.png see pic. using arch linux with i3 and rxvt-unicode-patched. thanks a lot.

**Comment by muennich** [comment] 2017-11-28 08:57
Duplicate of issue #6.

**Closed by muennich** 2017-11-28 08:57 UTC

**Comment by Evidlo** [comment] 2018-01-27 13:41
Can't tell if that's Weechat, but if it is you can use raw mode (Alt-l) to hide all the extra formatting so you can yank it.
